# Generated by Django 3.1.2 on 2020-10-20 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=10)),
            ],
        ),
    ]
