# Generated by Django 3.1.2 on 2020-10-22 15:01

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=api.models.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=api.models.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=api.models.DateTimeWithoutTZField(),
        ),
    ]
